### ISSUE TITLE
Trim scheduling export (remove blanks lines)

### ISSUE THREAD

**Issue by kurtlawrence** [precision-mining-consulting/merz#6]

**Comment by npdelaney** [comment]
To clarify, do you mean lines for non-productive processes or something else?

![image](https://github.com/precision-mining-consulting/merz/assets/31809766/129b3685-670c-4f4b-80f7-0524d3a22e87)

**Comment by kurtlawrence** [comment]
In the form, the blank lines start to clutter the memo edit
